In [41]:
import pandas as pd
import numpy as np

In [42]:
pd.set_option('display.max_columns',65)

In [43]:
df=pd.read_csv("clean_data.csv")

In [44]:
df.head()

parcelid  airconditioningtypeid  bedroomcnt  buildingqualitytypeid  \
0  17073783                    5.0         3.0               6.015461   
1  17088994                    5.0         2.0               6.015461   
2  17100444                    5.0         3.0               6.015461   
3  17102429                    5.0         2.0               6.015461   
4  17109604                    5.0         4.0               6.015461   

   calculatedbathnbr  calculatedfinishedsquarefeet    fips  fireplacecnt  \
0                2.5                        1264.0  6111.0           0.0   
1                1.0                         777.0  6111.0           0.0   
2                2.0                        1101.0  6111.0           0.0   
3                1.5                        1554.0  6111.0           1.0   
4                2.5                        2415.0  6111.0           1.0   

   fullbathcnt  garagecarcnt  garagetotalsqft  hashottuborspa  \
0          2.0           2.0            434.0           False   
1          1.0           1.0            434.0           False   
2          2.0           2.0            441.0           False   
3          1.0           2.0            460.0           False   
4          2.0           2.0            665.0           False   

   heatingorsystemtypeid   latitude   longitude  lotsizesquarefeet  poolcnt  \
0                    2.0  34.303597 -119.287236             1735.0      0.0   
1                    2.0  34.272866 -119.198911             7200.0      0.0   
2                    2.0  34.340801 -119.079610             6569.0      0.0   
3                    2.0  34.354313 -119.076405             7400.0      0.0   
4                    2.0  34.266578 -119.165392             6326.0      0.0   

  propertycountylandusecode  propertylandusetypeid  rawcensustractandblock  \
0                      1128                  265.0          61110022003007   
1                      1129                  266.0          61110015031002   
2                      1111                  261.0          61110007011007   
3                      1110                  261.0          61110008002013   
4                      1111                  261.0          61110014021007   

   regionidcity  roomcnt  unitcnt  yearbuilt  numberofstories  fireplaceflag  \
0       34543.0      5.0      1.0     1986.0              2.0          False   
1       34543.0      4.0      1.0     1990.0              1.0          False   
2       26965.0      5.0      1.0     1956.0              1.0          False   
3       26965.0      5.0      1.0     1965.0              1.0           True   
4       34543.0      8.0      1.0     1984.0              2.0           True   

   structuretaxvaluedollarcnt  taxvaluedollarcnt  assessmentyear  \
0                    115087.0           191811.0          2015.0   
1                    143809.0           239679.0          2015.0   
2                     33619.0            47853.0          2015.0   
3                     45609.0            62914.0          2015.0   
4                    277000.0           554000.0          2015.0   

   landtaxvaluedollarcnt  taxamount taxdelinquencyflag  taxdelinquencyyear  \
0                76724.0    2015.06                  N                 NaN   
1                95870.0    2581.30                  N                 NaN   
2                14234.0     591.64                  N                 NaN   
3                17305.0     682.78                  N                 NaN   
4               277000.0    5886.92                  N                 NaN   

   logerror transactiondate  setyear  pooltype  zipcode  
0    0.0953      2016-01-27     2016         0    93001  
1    0.0198      2016-03-30     2016         0    93004  
2    0.0060      2016-05-27     2016         0    93066  
3   -0.0566      2016-06-07     2016         0    93060  
4    0.0573      2016-08-08     2016         0    93004

In [45]:
df=df.drop('transactiondate',axis=1)
df=df.drop('taxdelinquencyyear',axis=1)
def hottub(a):
    if a:
        return 1
    else:
        return 0
df['hashottuborspa']=df['hashottuborspa'].map(lambda a:hottub(a))

def fire(a):
    if a:
        return 1
    else:
        return 0
df['fireplaceflag']=df['fireplaceflag'].map(lambda a:fire(a))

def tax(a):
    if a=='Y':
        return 1
    else:
        return 0
df['taxdelinquencyflag']=df['taxdelinquencyflag'].map(lambda a:tax(a))

fips = pd.get_dummies(df['fips'])
df = df.join(fips)

yr = pd.get_dummies(df['setyear'])
df = df.join(yr)

ac = pd.get_dummies(df['airconditioningtypeid'], prefix='ac')
df = df.join(ac)

heat = pd.get_dummies(df['heatingorsystemtypeid'], prefix='heat')
df=df.join(heat)


In [46]:
from sklearn.model_selection import train_test_split

In [47]:
array=df.values

In [48]:
Y=array[:,32]

In [49]:
x1=array[:,2:6]
x2=array[:,7:12]
x3=array[:,13:17]
x4=array[:,19:20]
x5=array[:,21:32]  
x6=array[:,34:59]

In [50]:
X=np.hstack((x1,x2))
X=np.hstack((X,x3))
X=np.hstack((X,x4))
X=np.hstack((X,x5))
X=np.hstack((X,x6))

In [51]:
X[1]

array([2.0, 6.015460983643267, 1.0, 777.0, 0.0, 1.0, 1.0, 434.0, 0,
       34.272866, -119.19891100000001, 7200.0, 0.0, 61110015031002, 4.0,
       1.0, 1990.0, 1.0, 0, 143809.0, 239679.0, 2015.0, 95870.0, 2581.3, 0,
       0, 93004, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=object)

In [52]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [53]:
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

In [54]:
X_train

array([[5.0, 4.0, 3.0, ..., 0, 0, 0],
       [4.0, 6.0, 3.0, ..., 0, 0, 0],
       [3.0, 7.0, 2.0, ..., 0, 0, 0],
       ..., 
       [2.0, 6.015460983643267, 2.0, ..., 0, 0, 0],
       [3.0, 6.015460983643267, 2.0, ..., 0, 0, 0],
       [3.0, 7.0, 2.0, ..., 0, 0, 0]], dtype=object)

In [55]:
#http://blog.datadive.net/selecting-good-features-part-iv-stability-selection-rfe-and-everything-side-by-side/
model=LinearRegression()
rfe = RFE(model, n_features_to_select=25)
rfe.fit(X_train,Y_train)

RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False),
  n_features_to_select=25, step=1, verbose=0)

In [56]:
rfe.ranking_ 

array([ 9, 13, 12, 19,  3,  6, 16, 17,  8, 10,  4, 25,  5, 26, 14,  7, 18,
       11,  2, 23, 22,  1, 24, 21,  1, 15, 20,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [57]:
prediction=rfe.predict(X_test)

In [58]:
Y_test

array([-0.006999999999999999, -0.0131, 0.008, ..., -0.512303713577, 0.0286,
       -0.0199167020436], dtype=object)

In [59]:
from sklearn.metrics import mean_squared_error
from math import sqrt

print(sqrt(mean_squared_error(Y_test, prediction)))

0.16483046927443837


In [60]:
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(Y_test,prediction))

0.0700219857887


In [61]:
# use cannot use MAPE because cannot divide by zero, use SMAPE instead
# https://math.stackexchange.com/questions/677852/how-to-calculate-relative-error-when-true-value-is-zero
# https://en.wikipedia.org/wiki/Symmetric_mean_absolute_percentage_error

y_true = np.array(Y_test)
y_score = np.array(prediction)

np.mean(np.abs(y_true - y_score) / (np.abs(y_true) + np.abs(y_score))) * 100

72.51097639315104